package hzhl.net.hlcall.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import hzhl.net.hlcall.entity.BlacklistEntity;
import hzhl.net.hlcall.entity.IntercomEntity;
import hzhl.net.hlcall.entity.MeetingEntity;
import hzhl.net.hlcall.entity.SettingEntity;
import hzhl.net.hlcall.entity.SipProfileEntity;
import hzhl.net.hlcall.entity.SipProfileLoginEntity;

import hzhl.net.hlcall.entity.BlacklistEntityDao;
import hzhl.net.hlcall.entity.IntercomEntityDao;
import hzhl.net.hlcall.entity.MeetingEntityDao;
import hzhl.net.hlcall.entity.SettingEntityDao;
import hzhl.net.hlcall.entity.SipProfileEntityDao;
import hzhl.net.hlcall.entity.SipProfileLoginEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig blacklistEntityDaoConfig;
    private final DaoConfig intercomEntityDaoConfig;
    private final DaoConfig meetingEntityDaoConfig;
    private final DaoConfig settingEntityDaoConfig;
    private final DaoConfig sipProfileEntityDaoConfig;
    private final DaoConfig sipProfileLoginEntityDaoConfig;

    private final BlacklistEntityDao blacklistEntityDao;
    private final IntercomEntityDao intercomEntityDao;
    private final MeetingEntityDao meetingEntityDao;
    private final SettingEntityDao settingEntityDao;
    private final SipProfileEntityDao sipProfileEntityDao;
    private final SipProfileLoginEntityDao sipProfileLoginEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        blacklistEntityDaoConfig = daoConfigMap.get(BlacklistEntityDao.class).clone();
        blacklistEntityDaoConfig.initIdentityScope(type);

        intercomEntityDaoConfig = daoConfigMap.get(IntercomEntityDao.class).clone();
        intercomEntityDaoConfig.initIdentityScope(type);

        meetingEntityDaoConfig = daoConfigMap.get(MeetingEntityDao.class).clone();
        meetingEntityDaoConfig.initIdentityScope(type);

        settingEntityDaoConfig = daoConfigMap.get(SettingEntityDao.class).clone();
        settingEntityDaoConfig.initIdentityScope(type);

        sipProfileEntityDaoConfig = daoConfigMap.get(SipProfileEntityDao.class).clone();
        sipProfileEntityDaoConfig.initIdentityScope(type);

        sipProfileLoginEntityDaoConfig = daoConfigMap.get(SipProfileLoginEntityDao.class).clone();
        sipProfileLoginEntityDaoConfig.initIdentityScope(type);

        blacklistEntityDao = new BlacklistEntityDao(blacklistEntityDaoConfig, this);
        intercomEntityDao = new IntercomEntityDao(intercomEntityDaoConfig, this);
        meetingEntityDao = new MeetingEntityDao(meetingEntityDaoConfig, this);
        settingEntityDao = new SettingEntityDao(settingEntityDaoConfig, this);
        sipProfileEntityDao = new SipProfileEntityDao(sipProfileEntityDaoConfig, this);
        sipProfileLoginEntityDao = new SipProfileLoginEntityDao(sipProfileLoginEntityDaoConfig, this);

        registerDao(BlacklistEntity.class, blacklistEntityDao);
        registerDao(IntercomEntity.class, intercomEntityDao);
        registerDao(MeetingEntity.class, meetingEntityDao);
        registerDao(SettingEntity.class, settingEntityDao);
        registerDao(SipProfileEntity.class, sipProfileEntityDao);
        registerDao(SipProfileLoginEntity.class, sipProfileLoginEntityDao);
    }
    
    public void clear() {
        blacklistEntityDaoConfig.clearIdentityScope();
        intercomEntityDaoConfig.clearIdentityScope();
        meetingEntityDaoConfig.clearIdentityScope();
        settingEntityDaoConfig.clearIdentityScope();
        sipProfileEntityDaoConfig.clearIdentityScope();
        sipProfileLoginEntityDaoConfig.clearIdentityScope();
    }

    public BlacklistEntityDao getBlacklistEntityDao() {
        return blacklistEntityDao;
    }

    public IntercomEntityDao getIntercomEntityDao() {
        return intercomEntityDao;
    }

    public MeetingEntityDao getMeetingEntityDao() {
        return meetingEntityDao;
    }

    public SettingEntityDao getSettingEntityDao() {
        return settingEntityDao;
    }

    public SipProfileEntityDao getSipProfileEntityDao() {
        return sipProfileEntityDao;
    }

    public SipProfileLoginEntityDao getSipProfileLoginEntityDao() {
        return sipProfileLoginEntityDao;
    }

}
